const clientsData = [
    {
      id: 1,
      name: 'John Doe',
      dateOfBirth: '1980-05-12',
      gender: 'Male',
      homeAddress: '1234 Elm St, Springfield, IL',
      email: 'johndoe@example.com',
      phoneNumbers: ['(555) 555-5555'],
      socialSecurityNumber: 'XXX-XX-1234',
      maritalStatus: 'Married',
      occupation: 'Software Engineer',
      employmentStatus: 'Employed',
      incomeLevel: '$100,000',
      dependents: 2,
      drivingLicenseNumber: 'D12345678',
      previousClaimsHistory: 'No claims',
      creditHistory: 'Excellent',
      healthHistory: 'Good',
      lifestyleInfo: 'Non-smoker, regular exercise',
      beneficiaries: 'Spouse and 2 children',
      occupationRisk: 'Low',
      policyNumber: 'P1234567890',
      policyType: 'Homeowner Insurance',
      policyStartDate: '2021-01-01',
      policyExpirationDate: '2022-12-31',
      policyPremium: '$1,200/year',
      premiumPaymentFrequency: 'Annual',
      coverageLimits: '$250,000',
      deductible: '$1,000',
      endorsementsRiders: 'Valuable items coverage',
      exclusions: 'Flood damage',
      policyholderContribution: '$1,000',
      policyStatus: 'Active',
      insuredAssetInfo: 'Single-family home, built in 2000',
      claimsHistory: 'No claims',
      policyRenewalDate: '2022-12-31',
      underwritingInfo: 'Completed',
      discountsApplied: 'Multi-policy discount',
      insuranceAgent: 'Jane Doe',
      reinsuranceDetails: 'Reinsured by Global Reinsurance Co.',
      policyholderPreferences: 'Paperless billing',
    },
    {
      id: 2,
      name: 'Jane Smith',
      dateOfBirth: '1990-07-21',
      gender: 'Female',
      homeAddress: '5678 Oak St, Metropolis, NY',
      email: 'janesmith@example.com',
      phoneNumbers: ['(555) 555-1234'],
      socialSecurityNumber: 'XXX-XX-5678',
      maritalStatus: 'Single',
      occupation: 'Graphic Designer',
      employmentStatus: 'Freelancer',
      incomeLevel: '$80,000',
      dependents: 0,
      drivingLicenseNumber: 'S987654321',
      previousClaimsHistory: 'Minor car accident (2020)',
      creditHistory: 'Good',
      healthHistory: 'Fair',
      lifestyleInfo: 'Occasional smoker',
      beneficiaries: 'None',
      occupationRisk: 'Moderate',
      policyNumber: 'P9876543210',
      policyType: 'Car Insurance',
      policyStartDate: '2020-05-01',
      policyExpirationDate: '2023-04-30',
      policyPremium: '$600/year',
      premiumPaymentFrequency: 'Monthly',
      coverageLimits: '$100,000',
      deductible: '$500',
      endorsementsRiders: 'Roadside assistance',
      exclusions: 'Racing incidents',
      policyholderContribution: '$500',
      policyStatus: 'Active',
      insuredAssetInfo: '2018 Toyota Corolla',
      claimsHistory: '1 minor claim',
      policyRenewalDate: '2023-04-30',
      underwritingInfo: 'Completed',
      discountsApplied: 'Safe driver discount',
      insuranceAgent: 'Mark Johnson',
      reinsuranceDetails: 'Reinsured by National Re',
      policyholderPreferences: 'Monthly payments, paperless billing',
    },
  ];

  export default clientsData;